# Generated by Django 4.1.2 on 2023-01-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='whale',
            table='whale_table',
        ),
    ]
